'use client';
import { useState } from 'react';
import LiquidGlass from './liquid-glass';
import ModernHero from './modern-hero';
import { ArrowUpRight, ArrowRight, Globe2, Activity, Network, Building2, Cpu, Menu, X, Plus, Minus, Zap } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
const base='https://global.cet-electric.com/sg';
const directions=[['modern','01','Modern'],['enterprise','02','Enterprise'],['trendy','03','Trendy + Interaction'],['glass','04','Liquid Glass']];
const solutions=[{name:'Data centers',icon:Network,title:'Intelligence for always-on infrastructure.',body:'Bring power, cooling and building systems into one view. Connect critical infrastructure with CET’s data center management solutions.',url:'/Datacenter',tag:'CONNECTED INFRASTRUCTURE'}, {name:'Power quality',icon:Activity,title:'See the quality behind every kilowatt.',body:'Understand electrical performance with power quality monitoring and the measurement devices that turn complex signals into actionable information.',url:'/DATACENTER/list.aspx?lcid=179',tag:'POWER YOU CAN UNDERSTAND'}, {name:'Smart buildings',icon:Building2,title:'Make every building more informed.',body:'Connect building systems and energy consumption data to support day-to-day operation, monitoring and control.',url:'/DATACENTER/list.aspx?lcid=173',tag:'BUILDING INTELLIGENCE'}, {name:'Energy optimization',icon:Zap,title:'Turn energy insight into better decisions.',body:'Explore AI energy optimization alongside CET’s monitoring and management systems for more efficient operations.',url:'/DATACENTER/list.aspx?lcid=172',tag:'A MORE EFFICIENT FUTURE'}];
const products=[['01','Power quality meters','Precision at the point of measurement.','/device/list141'],['02','Multi-circuit monitors','A clearer view of distributed loads.','/device/list144'],['03','Gateways & processors','Bring your devices and systems together.','/device/list145']];
function Link({to,children,className=''}:{to:string,children:React.ReactNode,className?:string}){return <a className={className} href={to.startsWith('#')?to:base+to}>{children}</a>}
function Website({style}:{style:string}){const [menu,setMenu]=useState(false);const [active,setActive]=useState(0);const [open,setOpen]=useState<number|null>(0);const s=solutions[active];return <div className={`website ${style}`}>
{style==='enterprise'&&<div className="utility"><span>CET Singapore · Global expertise. Local support.</span><span>+65 6669 7158 <span className="divider">|</span> Singapore / EN</span></div>}
<header className="site-nav"><a href="#" aria-label="CET homepage" className="brand"><img src="/assets/logo.svg" alt="CET"/><span>Energy intelligence</span></a><nav aria-label="Main navigation" className={menu?'is-open':''}>{['Solutions','Products','About','Resources'].map(n=><a key={n} href={'#'+n.toLowerCase()} onClick={()=>setMenu(false)}>{n}</a>)}</nav><div className="nav-right"><span className="locale"><Globe2 size={16}/> EN</span><Link to="/CustomerSupport" className="contact">Let’s talk <ArrowUpRight size={17}/></Link><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
<main>
{style==='modern'?<ModernHero/>:<section className="hero">
<div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> {style==='enterprise'?'INTEGRATED ENERGY & POWER SOLUTIONS':style==='trendy'?'THE NEXT CHAPTER OF ENERGY':'ENGINEERED FOR A CONNECTED WORLD'}</div><h1>{style==='modern'?<>Better energy.<br/><em>By design.</em></>:style==='enterprise'?<>Confidence in<br/>every connection.</>:<>MORE<br/><em>POWER.</em><br/>LESS GUESSWORK.</>}</h1><p>From precision metering to intelligent systems, we help you understand, manage and optimize the energy that moves your world.</p><div className="hero-actions"><a className="primary" href="#solutions">Explore solutions <ArrowUpRight size={20}/></a><a className="text-link" href="#products">Discover our products <ArrowRight size={18}/></a></div>{style==='enterprise'&&<div className="hero-proof">Commercial · Industrial · Utilities</div>}</div>
<div className="hero-visual"><div className="visual-top"><span>PRECISION. CONNECTED.</span><Activity size={24}/></div><div className="product-stage"><img src="/assets/meters.png" alt="CET power quality monitoring devices"/></div><div className="visual-bottom"><div><span className="small-label">INTELLIGENCE STARTS HERE</span><strong>Designed for reliability.<br/>Manufactured to last.</strong></div><a href="#products" className="circle-arrow" aria-label="Explore CET products"><ArrowUpRight/></a></div><div className="stage-index">CET / POWER QUALITY SERIES</div></div>
{style==='trendy'&&<div className="ticker" aria-hidden="true"><span>MEASURE BETTER ↗ CONNECT SMARTER ↗ THINK FORWARD ↗ MEASURE BETTER ↗ CONNECT SMARTER ↗ THINK FORWARD ↗</span></div>}
</section>}
<section id="about" className="proof"><div className="proof-intro"><span className="eyebrow">BUILT ON EXPERIENCE</span><h2>Global expertise.<br/>Real-world impact.</h2></div>{[['1,700+','Employees'],['12+','Worldwide distributors'],['4','R&D centers']].map(([n,l])=><div className="stat" key={l}><strong>{n}</strong><span>{l}</span></div>)}</section>
<section id="solutions" className="solutions section-pad"><div className="section-heading"><div><span className="eyebrow">01 / SOLUTIONS</span><h2>Connected thinking.<br/><em>Across every system.</em></h2></div><p>One connected approach to complex energy challenges. Find the right starting point for your operation.</p></div><Tabs value={String(active)} onValueChange={v=>setActive(Number(v))} className="solution-tabs"><TabsList className="solution-tab-list" aria-label="Explore solutions">{solutions.map((v,i)=><TabsTrigger key={v.name} value={String(i)}><v.icon size={18}/>{v.name}</TabsTrigger>)}</TabsList>{solutions.map((_,i)=><TabsContent value={String(i)} key={i}><div className="solution-detail"><div className="solution-copy"><span className="eyebrow">{s.tag}</span><h3>{s.title}</h3><p>{s.body}</p><Link to={s.url} className="text-link">Explore solution <ArrowUpRight size={19}/></Link></div><div className="system-view"><img src="/assets/software.png" alt="CET energy management software interface across multiple displays"/><span>Devices → Connected systems → Clearer decisions</span></div></div></TabsContent>)}</Tabs></section>
<section id="products" className="products section-pad"><div className="section-heading"><div><span className="eyebrow">02 / PRODUCTS</span><h2>Small details.<br/><em>Powerful possibilities.</em></h2></div><Link to="/Products" className="text-link">View all products <ArrowUpRight size={19}/></Link></div><div className="product-grid">{products.map(([n,title,desc,url])=><Link key={n} to={url} className="product-card"><span className="product-number">{n} / DEVICE</span><div className="product-icon">{n==='01'?<Activity/>:n==='02'?<Cpu/>:<Network/>}</div><h3>{title}</h3><p>{desc}</p><span className="product-bottom">Explore range <ArrowUpRight size={20}/></span></Link>)}</div></section>
<section id="resources" className="resources section-pad"><div><span className="eyebrow">03 / ENGINEERING RESOURCES</span><h2>Everything you need.<br/><em>Right where you need it.</em></h2><p>From selection to installation, get the technical information that keeps your project moving.</p></div><div className="resource-list">{[['Product documentation','Catalogues, datasheets and installation guidance.','/Catalogue','Browse catalogues'],['Software & systems','Explore software for CET devices and energy management.','/iEMSSoftware','Find software'],['Technical knowledge','Practical guidance and technical notes for your team.','/Sop','Visit knowledge base']].map(([title,desc,url,cta],i)=><div className="resource-item" key={title}><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i} aria-controls={`resource-${style}-${i}`}>{title}{open===i?<Minus size={20}/>:<Plus size={20}/>}</button>{open===i&&<div id={`resource-${style}-${i}`}><p>{desc}</p><Link to={url} className="text-link">{cta} <ArrowUpRight size={17}/></Link></div>}</div>)}</div></section>
<section className="closing"><span className="eyebrow">LET’S BUILD WHAT’S NEXT</span><h2>Your next challenge.<br/>Our shared ambition.</h2><Link to="/CustomerSupport" className="primary">Talk to CET <ArrowUpRight size={20}/></Link></section>
</main><footer><div className="footer-brand"><img src="/assets/logo.svg" alt="CET"/><p>Making electric energy safer,<br/>more reliable and more efficient.</p></div><div><strong>CET Singapore</strong><a href="tel:+6566697158">+65 6669 7158</a><Link to="/About">About CET <ArrowUpRight size={14}/></Link></div><div><strong>Explore</strong><Link to="/Products">Products</Link><Link to="/News">News & events</Link><Link to="/CustomerSupport">Contact</Link></div><div className="footer-bottom"><span>CET Singapore Pte. Ltd. · Independent redesign concept</span><a href={base+'/'}>Original CET website ↗</a></div></footer>
</div>}
export default function Home(){const [style,setStyle]=useState('modern');return <Tabs value={style} onValueChange={v=>setStyle(String(v))} className="design-app"><div className="design-bar"><div className="design-label"><span className="design-dot"/> CET / DESIGN DIRECTIONS</div><TabsList className="design-switcher" aria-label="Choose website design">{directions.map(([id,n,name])=><TabsTrigger value={id} key={id}><span>{n}</span>{name}</TabsTrigger>)}</TabsList><span className="concept-label">HOMEPAGE CONCEPTS</span></div>{directions.map(([id])=><TabsContent value={id} key={id}>{id==='glass'?<LiquidGlass/>:<Website style={id}/>}</TabsContent>)}</Tabs>}
